### ISSUE TITLE
请教 不需要效果也一样,少hook一个函数 更安全?

### ISSUE THREAD

**Issue by zhichengfalv** [yulingtianxia/TBUIAutoTest#1]

**Comment by wg689** [comment]
- (NSString *)tb_accessibilityLabel,这个可以去掉,少hook一个函数 更安全

**Comment by yulingtianxia** [comment]
@wg689 当时是因为发现一些控件只能在accessibilityLabel 中 hook，可能是系统的 bug，跟版本有关。顺便问下你看到的『别人的代码』能提供下链接么？

**Comment by wg689** [comment]
https://testerhome.com/topics/6642  这个文章,那些控件什么情况只能在accessibilityLabel中hook 啊,试了下hook action 和initTarget 的方法,获得函数名字


`#pragma mark - Method Swizzling
- (void)tb_addTarget:(id)target action:(SEL)action forControlEvents:(UIControlEvents)controlEvents{
//    NSLog(@"方法:%@,%lu",NSStringFromSelector(action) ,(unsigned long)controlEvents);
    [self setName:NSStringFromSelector(action)];
    [self tb_addTarget:target action:action forControlEvents:controlEvents];
}



// 每个控件创建就会调用
- (NSString *)tb_accessibilityIdentifier
{
    NSString *accessibilityIdentifier = [self tb_accessibilityIdentifier];
    [self runTests];
    
    // button 和UISwitch 特殊处理
    if ([self isKindOfClass:[UIButton class]]) {
        self.accessibilityValue = [NSString stringWithFormat:@"%@Button_%d",IDTAG,((UIButton *)self).selected];
    }
    if ([self isKindOfClass:[UISwitch class]]) {
        self.accessibilityValue =  [NSString stringWithFormat:@"%@Switch_%d",IDTAG,((UISwitch *)self).on];
    }
    
    
    if ([self isKindOfClass:[UITableViewCell class]]) {//UITableViewCell 特殊处理
        self.accessibilityIdentifier = [NSString stringWithFormat:@"%@+%@",IDTAG,((UITableViewCell *)self).reuseIdentifier];
        return self.accessibilityIdentifier;
    }
    
    
    
    if (accessibilityIdentifier.length > 0 && [[accessibilityIdentifier substringToIndex:3] isEqualToString:IDTAG]) {
        return accessibilityIdentifier;
    } else if ([accessibilityIdentifier isEqualToString:@"null"]) {
        accessibilityIdentifier = @"";
    }
    
    // 当前控件找到父控件中的实例化的名字
    NSString *labelStr = [self.superview findNameWithInstance:self];
    
    if (labelStr && ![labelStr isEqualToString:@""]) {//存在且不为空
        labelStr = [NSString stringWithFormat:@"%@%@",IDTAG,labelStr];
    }
    else {//lableStr 为空
        // 动态文本不会来这里,静态文本才会来这里
        if ([self isKindOfClass:[UILabel class]]) {//UILabel 使用 text
            labelStr = [NSString stringWithFormat:@"%@%@",IDTAG,((UILabel *)self).text?:@""];
        }
        else if ([self isKindOfClass:[UIImageView class]]) {//UIImageView 使用 image 的 imageName
            labelStr = [NSString stringWithFormat:@"%@%@",IDTAG,((UIImageView *)self).image.accessibilityIdentifier?:[NSString stringWithFormat:@"image%ld",(long)((UIImageView *)self).tag]];
        }
        else if ([self isKindOfClass:[UIButton class]]) {//UIButton 使用 button 的 text 和 image
            
    
                labelStr = [NSString stringWithFormat:@"%@%@%@",IDTAG,((UIButton *)self).titleLabel.text?:@"",((UIButton *)self).imageView.image.accessibilityIdentifier?:@""];
        }
        
        // 删掉不获取lable 的文本信息
    }
    
    // 如果为空的话 使用父类名称和子类名称拼接
    if ([labelStr isEqualToString:IDTAG] || [labelStr isEqualToString:[NSString stringWithFormat:@"%@null",IDTAG ]]) {
        labelStr = @"";
    }
    if([labelStr  isEqualToString:@""]|| [labelStr  isEqualToString:@"(null)"]||[labelStr  isEqualToString:@"null"]||labelStr.length == 0){
        
        NSString *actionStr = [self name];//
        if (![self isEmpty:actionStr]) {
            labelStr = actionStr;
        }else{
            labelStr = [NSString stringWithFormat:@"%@_%@",[self.superview class],[self class]];
        }
    }
    
    //赋值id
    [self setAccessibilityIdentifier:labelStr];// 可不要
    return labelStr;// 这里才是真正的赋值
}
`

**Comment by wg689** [comment]
有些id 获取不到 只能给个父类名字和子类名字 拼接 你那有好的方案没?
