### ISSUE TITLE
 crash,but u tell me not worry?how 2 solve the crash problem, without debug log

### ISSUE THREAD

**Issue by BigYiza** [yulingtianxia/TBUIAutoTest#3]
information:
crash in ：iphone4, iOS8.0
but run normal in other device

![](https://user-images.githubusercontent.com/15795722/37700040-095df3aa-2d25-11e8-95c2-452a53b102e9.png)

**Comment by yulingtianxia** [comment]
@zGbear 麻烦发下 stringType 是啥，最好能把这些变量都截下来。这里是系统 API 的问题，我看看有没有办法绕过

**Comment by BigYiza** [comment]
![image](https://user-images.githubusercontent.com/15795722/37754602-22b769e0-2ddd-11e8-8bc6-39dd55def2e2.png)

能打印出来的信息有限  有没有log日志  你看下呢

**Comment by yulingtianxia** [comment]
@zGbear 如果能知道这个类的第5个成员变量是啥就好了，肯定是苹果对这个成员变量类型不兼容。

**Comment by BigYiza** [comment]
打印出来就是个地址，没办法知道，比较难搞

**Comment by yulingtianxia** [comment]
@zGbear 如果能知道这个类的第5个成员变量是啥就好了，肯定是苹果对这个成员变量类型不兼容。

**Comment by yulingtianxia** [comment]
@zGbear 这个类的类名是啥呢？如果是自定义的类，看看你们添加了啥成员变量，有没有可疑的。

**Comment by BigYiza** [comment]
![image](https://user-images.githubusercontent.com/15795722/37810725-c32c6d5e-2e90-11e8-95c3-5839aa2b5912.png)

UITransitionView ：the superview of a UITableView which is inside of a UINavigationController which is inside of a UITabBarController.

再往下的成员就打不出来了

**Comment by BigYiza** [comment]
![image](https://user-images.githubusercontent.com/15795722/37810878-b8ebd680-2e91-11e8-837c-6abf09e2a5c6.png)
补充一下堆栈信息

**Comment by yulingtianxia** [comment]
@zGbear  UITransitionView 看起来并不需要打标签，如果每次都 crash 在这个类上的话，可以考虑在 github 维护个黑名单过滤下。

**Comment by BigYiza** [comment]
嗯嗯  我先手动过滤下

**Comment by yulingtianxia** [comment]
@zGbear 1.1.8 新版本还会 crash 么？

**Comment by BigYiza** [comment]
换了个工作  没用这套UI测试框架了  我让接锅的同学跟进一下呢
