### ISSUE TITLE
导航栏的按钮设置accessibilityid失败

### ISSUE THREAD

**Issue by 0xIce** [yulingtianxia/TBUIAutoTest#4]
1.![image](https://user-images.githubusercontent.com/9348287/37751758-28e29b4a-2dcf-11e8-8c5a-9ed654b15623.png)
如题
2. 如果button的图片是网络获取设置的id变成了image0
![image](https://user-images.githubusercontent.com/9348287/37751810-6fb927a0-2dcf-11e8-82ec-b69e7f77f87b.png)
3. 循环创建的label设置id失败
![image](https://user-images.githubusercontent.com/9348287/37751830-8ea45ab8-2dcf-11e8-8a81-94642342f4b4.png)

**Comment by yulingtianxia** [comment]
@hotchner 可是尝试给 image 和 label 设置 tag，自己保证唯一且不变就行
