### ISSUE TITLE
标签怎么唯一确定？

### ISSUE THREAD

**Issue by dexterhahaha** [yulingtianxia/TBUIAutoTest#6]

**Comment by yulingtianxia** [comment]
@JunyiXie 成员变量名不会重复。

**Comment by shaop** [comment]
大神，还是一样的问题，如果页面是一个 tableView ，里面 n 个相同的 Cell ，每个 Cell 里面的控件的标签都是成员变量了。这样不是重复了吗？

**Comment by chuckern** [comment]
没有去提新的issue 想在这里问一下.
对于属性和局部变量如何确保标签唯一了解了, 但是对于像批量生产`cell`这种场景.
1. 他不是属性.
2. 是局部变量但是内容未知 后台下发的.

好奇这样的UI标签 那边有什么好的解决方案么.
