### ISSUE TITLE
标签是如何添加的？

### ISSUE THREAD

**Issue by FMYang** [yulingtianxia/TBUIAutoTest#7]
accessibilityIdentifier是在长按某个视图的时候，给这个视图添加的吗？还是程序启动后，给所有视图自动添加的？
如果是长按的时候添加的话，如果所有的视图都需要标签，得全部长按一遍吗？
目前只看到设置imageName的时候，自动添加了accessibilityIdentifier，期待解答。
```objectivec
+ (UIImage *)tb_imageNamed:(NSString *)imageName{
    UIImage *image = [UIImage tb_imageNamed:imageName];
    image.accessibilityIdentifier = imageName;
    return image;
}
```

**Comment by yulingtianxia** [comment]
@FMYang 标签是懒加载的，只有你需要用到的时候，才会生成。不是启动后给所有视图都加一遍标签。

**Comment by FMYang** [comment]
@yulingtianxia 

```objectivec
 if ([name hasPrefix:@"_"]) {  //去掉变量名的下划线前缀
        name = [name substringFromIndex:1];
   }
```
swift4.2中变量名是以 .storage结尾的，不是‘_’开头的，截取下划线的方式获取变量名不适用于swift

一开始以为是自动打标签的，这样使用Appium等自动化测试工具编写脚本就方便了，楼主是否考虑过支持下自动全局打标签？

**Comment by yulingtianxia** [comment]
@FMYang 就是全局自动打标签呀，然后用自动化测试脚本去抓。只是是懒加载，只有你去取标签的时候，才会给你生成标签。
我真对成员变量名只是去掉下划线而已，没有依赖下划线识别是否是成员变量，swift的后缀不去掉也无所谓的。

**Comment by FMYang** [comment]
我的工程是swift4.2写的，集成TBUIAutoTest后，都没有以变量名打标签

**Comment by FMYang** [comment]
我的工程是swift4.2写的，集成TBUIAutoTest后，没有以变量名打标签
![image](https://user-images.githubusercontent.com/3436190/44702117-60413c00-aac4-11e8-9399-46efdc8f91fd.png)
上面这段没走，请问是什么原因

**Comment by yulingtianxia** [comment]
@FMYang 能发下复现的 demo 么？目前还没试过 Swift 项目

**Comment by FMYang** [comment]
@yulingtianxia 
[TBUITestDemo.zip](https://github.com/yulingtianxia/TBUIAutoTest/files/2330511/TBUITestDemo.zip)

**Comment by yulingtianxia** [comment]
@FMYang 已经修复，试试 1.1.8 版本： https://github.com/yulingtianxia/TBUIAutoTest/releases/tag/1.1.8
